### PR TITLE
Active_Record Review 1.0.0

### PR DESCRIPTION
**Pull request by mimipeshy**
In this review we:- 

- [ ] Created Models for User, Comment, and Post and validated them

- [ ] We created associations for each of the above models

- [ ] We migrated the database tables which created the Schema

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @mimipeshy & @KossySteve  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
Currently, our project is incapable of performing some required functionalities. I have underpinned some of the required functionalities with a reference to the project's requirements from the Odin project below : 👇
## REQUIRED CHANGES
### Behaviour 
We have not implemented the necessary controllers for our models and there is no way of testing the behaviour of the respective models. For this to be seamless we need to implement the following controllers 👇 
- [x] Make sure we have a controller that allows for a user to be created. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingUser.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)).
- [x] Let's make sure in your project, that a post can also be created ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingPost.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)).
- [ ] A comment to the post can also be created ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)).
### General
- [ ] In our next round of project submission let's make sure we have provided the project with a more descriptive README.md to make it look more professional ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
 ##
- That's about it. If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey team, it's me again :wave:
-
My apologies as I was not clear in my previous review. 🙏 
We, however, do have some few changes to carry out before we proceed (see review comment).
##
The earlier required changes meant to address some issues that I unfortunately never put across clearly.
### Required 
- [x] Currently, the user, a post and comment to the post can be created with invalid credentials like nil. Kindly lets fix this. Let's ensure that only valid credentials are allowed during the creation of these objects. thank you. 

- Everything else looks neat. Apologies once more for any misleading the previous requirements might have caused. 

### OPTIONAL 
- [ ] Wouldn't it be nice if we add some test suites to check for the above requirements?
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by mimipeshy** [comment]
Thanks for clarifying the issue, we have fixed it.

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @mimipeshy  & @KossySteve! :+1:
- Go ahead and merge the changes. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by mimipeshy** [comment]
Thank you!!!

**Pull request merged**
